# Site settings
title: The Justice Trap
email: thejusticetrap@gmail.com
description: The Justice Trap is a multimedia collaboration between advocates and artists that combines interactive design and short documentaries that illustrate the unjust policies and practices that make up the criminal justice system
url: "http://thejusticetrap.org"
sass:
    sass_dir: assets/_sass
    style: compressed

# Build settings
markdown: kramdown
